---
- name: install epel and centos-release-scl-rh
  yum:
    name:
      - epel-release
      - centos-release-scl-rh
    state: '{{ silk_install }}'

- name: install cert-forensic-tools repo file
  yum:
    name:
      - https://forensics.cert.org/cert-forensics-tools-release-el7.rpm
    state: '{{ silk_install }}'

# https://tools.netsa.cert.org/silk/silk-on-box-rpm.html
- name: install the silk stack
  yum:
    name:
      - libfixbuf
      - silk-common
      - silk-analysis
      - silk-rwflowpack
      - yaf
      - tcpdump
    state: '{{ silk_install }}'

- name: enable rwflowpack
  lineinfile:
    path: /etc/sysconfig/rwflowpack.conf
    regexp: '^ENABLED='
    line: ENABLED=1

- name: set sensor_config path
  lineinfile:
    path: /etc/sysconfig/rwflowpack.conf
    regexp: '^SENSOR_CONFIG='
    line: 'SENSOR_CONFIG={{ silk_sensor_conf }}'

- name: create needed directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /var/lib/rwflowpack/archive
    - /data
    - /var/lib/rwflowpack/log

- name: create poll-directories
  file:
    path: '{{ item }}'
    state: directory
  loop: "{{ silk_sensors | product(['sensor']) | product(['poll_directory']) | list }}"

- name: copy silk.conf
  template:
    src: silk.conf.j2
    dest: "{{ silk_conf }}"
    owner: root
    group: root
    mode: 0644
  notify: restart rwflowpack

- name: copy sensor.conf
  template:
    src: sensor.conf.j2
    dest: "{{ silk_sensor_conf }}"
    owner: root
    group: root
    mode: 0644
  notify: restart rwflowpack

- name: enable and start rwflowpack
  systemd:
    name: rwflowpack
    enabled: yes
    state: started

#          - libfixbuf-ipfixDump
#          - silk-flowcap
#          - silk-rwflowappend
#          - silk-rwpollexec
#          - silk-rwreceiver
#          - silk-rwsender
#          - super_mediator
#          - analysis-pipeline
