# -*- mode: ruby -*-
# vi: set ft=ruby :

CURRENT_PATH = File.dirname(File.expand_path(__FILE__))

Vagrant.configure("2") do |config|
  boxes = [
    { :name => "centos7", :box => "centos/7" },
  ]
  last_octet = 10
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.box = opts[:box]
      config.vm.network "private_network", ip: "10.100.10.#{last_octet}"
      last_octet += 1
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
        vb.linked_clone = true
        # Workaround for Ubuntu Cloud init VMs (focal)
        # Create virtual serial port, output to file console-output.OS.
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", "file", "#{CURRENT_PATH}/console-output.#{opts[:name]}"]
      end
      if opts[:name] == boxes.last[:name]
        config.vm.provision "Update  CentOS 7", type: "shell", inline: <<-SHELL
           yum -y upgrade
        SHELL
        #config.vm.provision "ansible: check",  type: "ansible", run: "always" do |ansible|
        #  ansible.compatibility_mode = "2.0"
        #  ansible.playbook = "test.yml"
        #  ansible.limit = "all"
        #  ansible.raw_arguments = ["--check", "--diff"]
        #end
        config.vm.provision "ansible: run", type: "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "test.yml"
          ansible.limit = "all"
        end
      end
    end
  end
end
